# Checks that a pull request can build the Verdict jars

name: Verdict continuous build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 8, 11 ]
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Set up GraphViz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ matrix.os }}-m2

    - name: Run Maven build
      run: mvn -B install -Dtycho.localArtifacts=ignore --file tools/pom.xml
      env:
        GraphVizPath: /usr/bin
